rangeday=`expr 3600 \* 24`
lastmonth=`date -d '1 month ago' "+%s"`
last2month=`date -d '2 month ago' "+%s"`
lastmonth=`expr $lastmonth - $rangeday`
thismonth=`date "+%s"`
thismonth=`expr $thismonth - $rangeday`

lastmonth_date=`date -d @$lastmonth "+%Y-%m-%d %H:%M:%S"`
thismonth_date=`date -d @$thismonth "+%Y-%m-%d %H:%M:%S"`
lastmonth_like=`date -d @$lastmonth "+%Y%m"`
last2month_like=`date -d @$last2month "+%Y%m"`
dirpath="/home/rully"


#mysql -h 172.20.0.240 -ureport -pkaskus2014 -B kaskus_openx -e "select ox_clients.clientid as 'Client ID', ox_clients.clientname as 'Client Name', ox_campaigns.campaignid as 'Campaigns ID', ox_campaigns.campaignname as 'Campaigns Name', ox_campaigns.activate_time as 'Campaigns Activation Time', ox_campaigns.expire_time as 'Campaigns Expired Time', ox_campaigns.updated as 'Campaigns Updated', ox_zones.zoneid as 'Zone ID', ox_zones.zonename as 'Zone Name', ox_zones.description as 'Zone Description', ox_zones.updated as 'Zone Updated', ox_banners.bannerid as 'Banner ID', ox_banners.description as 'Banner Description', ox_banners.compiledlimitation as 'Compiled Limitation', ox_banners.comments as 'Comments', ox_banners.acls_updated as 'ACLS Updated' FROM ox_banners, ox_campaigns, ox_zones, ox_ad_zone_assoc, ox_clients WHERE (ox_banners.updated >= '$lastmonth_date') AND (ox_banners.updated < '$thismonth_date') AND (ox_banners.campaignid = ox_campaigns.campaignid) AND (ox_ad_zone_assoc.ad_id = ox_banners.bannerid) AND (ox_ad_zone_assoc.zone_id = ox_zones.zoneid) AND (ox_campaigns.clientid = ox_clients.clientid) AND (ox_zones.zoneid != 153) Order by ox_banners.campaignid;" > $dirpath/openx_by_bannerupdated.xls

mysql -h 172.20.0.240 -ureport -pkaskus2014 -B kaskus_openx -e "select ox_clients.clientid as 'Client ID', ox_clients.clientname as 'Client Name', ox_campaigns.campaignid as 'Campaigns ID', ox_campaigns.campaignname as 'Campaigns Name', ox_campaigns.activate_time as 'Campaigns Activation Time', ox_campaigns.expire_time as 'Campaigns Expired Time', ox_campaigns.updated as 'Campaigns Updated', ox_zones.zoneid as 'Zone ID', ox_zones.zonename as 'Zone Name', ox_zones.description as 'Zone Description', ox_zones.updated as 'Zone Updated', ox_banners.bannerid as 'Banner ID', ox_banners.description as 'Banner Description', ox_banners.compiledlimitation as 'Compiled Limitation', ox_banners.comments as 'Comments Updated', ox_banners.acls_updated as 'ACLS Updated' FROM ox_banners, ox_campaigns, ox_zones, ox_ad_zone_assoc, ox_clients WHERE (substring(ox_banners.compiledlimitation,21,6) = '$lastmonth_like') AND (ox_banners.campaignid = ox_campaigns.campaignid) AND (ox_ad_zone_assoc.ad_id = ox_banners.bannerid) AND (ox_ad_zone_assoc.zone_id = ox_zones.zoneid) AND (ox_campaigns.clientid = ox_clients.clientid) AND (ox_banners.status = 0) AND (ox_zones.zoneid != 153) Order by ox_banners.campaignid;" > $dirpath/openx"$lastmonth_like".xls

mysql -h 172.20.0.240 -ureport -pkaskus2014 -B kaskus_openx -e "select ox_clients.clientid as 'Client ID', ox_clients.clientname as 'Client Name', ox_campaigns.campaignid as 'Campaigns ID', ox_campaigns.campaignname as 'Campaigns Name', ox_campaigns.activate_time as 'Campaigns Activation Time', ox_campaigns.expire_time as 'Campaigns Expired Time', ox_campaigns.updated as 'Campaigns Updated', ox_zones.zoneid as 'Zone ID', ox_zones.zonename as 'Zone Name', ox_zones.description as 'Zone Description', ox_zones.updated as 'Zone Updated', ox_banners.bannerid as 'Banner ID', ox_banners.description as 'Banner Description', ox_banners.compiledlimitation as 'Compiled Limitation', ox_banners.comments as 'Comments Updated', ox_banners.acls_updated as 'ACLS Updated' FROM ox_banners, ox_campaigns, ox_zones, ox_ad_zone_assoc, ox_clients WHERE (substring(ox_banners.compiledlimitation,21,6) = '$last2month_like') AND (ox_banners.campaignid = ox_campaigns.campaignid) AND (ox_ad_zone_assoc.ad_id = ox_banners.bannerid) AND (ox_ad_zone_assoc.zone_id = ox_zones.zoneid) AND (ox_campaigns.clientid = ox_clients.clientid) AND (ox_banners.status = 0) AND (ox_zones.zoneid != 153) Order by ox_banners.campaignid;" > $dirpath/openx"$last2month_like".xls

sendemail -f statistic@kaskusnetworks.com -t raharja@kaskusnetworks.com,glen@kaskusnetworks.com,rully@kaskusnetworks.com -u "REPORT OPENX MONTHLY" -m "REPORT OPENX PER $lastmonth_date s/d $thismonth_date : \n\n\n Details information attached below. \n\n\n\n Regards, \n DBA" -a $dirpath/openx$lastmonth_like".xls" $dirpath/openx$last2month_like".xls" -s 103.6.117.20 > /dev/null  2>&1
#sendemail -f statistic@kaskusnetworks.com -t raharja@kaskusnetworks.com,rully@kaskusnetworks.com,glen@kaskusnetworks.com -u "REPORT OPENX MONTHLY" -m "REPORT OPENX PER $lastmonth_date s/d $thismonth_date : \n\n\n Details information attached below. \n\n\n\n Regards, \n DBA" -a $dirpath/openx_attachment1.xls $dirpath/openx_attachment2.xls $dirpath/openx_attachment3.xls -s 172.16.0.5 > /dev/null  2>&1
